### ISSUE TITLE
Add support for  ListDataProvider in generateFilterComponents fo use in Grid 

### ISSUE THREAD

**Issue by skoude** [mvysny/vaadin-on-kotlin#4]
It would be great if .generateFilterComponents() would support ListDataProvider also.. It does not currently support that, and If we try to use it, we get: 
`ERROR c.vaadin.server.DefaultErrorHandler -
java.lang.ClassCastException: com.github.vok.framework.LikeFilter cannot be cast to java.lang.Void`

**Comment by mvysny** [comment]
Good idea! Can you please post a full exception stacktrace?

**Comment by skoude** [comment]
Thanks, here you go: 
`10:42:16.466 [qtp1442291478-714] ERROR c.vaadin.server.DefaultErrorHandler -
java.lang.ClassCastException: com.github.vok.framework.LikeFilter cannot be cast to java.lang.Void
        at com.vaadin.data.provider.DataProvider$2.combineFilters(DataProvider.java:217)
        at com.vaadin.data.provider.ConfigurableFilterDataProviderWrapper.getFilter(ConfigurableFilterDataProviderWrapper.java:59)
        at com.vaadin.data.provider.DataProviderWrapper.size(DataProviderWrapper.java:86)
        at com.vaadin.data.provider.DataProviderWrapper.size(DataProviderWrapper.java:85)
        at com.vaadin.data.provider.DataCommunicator.getDataProviderSize(DataCommunicator.java:739)
        at com.vaadin.data.provider.DataCommunicator.sendDataToClient(DataCommunicator.java:329)
        at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:313)
        at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:126)
        at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124)
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:381)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:224)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)`

**Comment by mvysny** [comment]
Thanks! I believe that `ListDataProvider` expects filters to be `SerializablePredicate`, however that failed cast to `Void` looks suspicious. I need to investigate further.

**Comment by kskyle** [comment]
Thanks, would be great to have support for this 👍

**Comment by skoude** [comment]
Did you have any time to check this out?

**Comment by mvysny** [comment]
Actually I have implemented a new set of Filters to be used with Sql2o. I did some preliminary checks and they seem to be working with `ListDataProvider` quite nicely; see `FiltersTest.kt`, the `testInMemoryFilters()` method.

**Comment by mvysny** [comment]
Please let me know whether this works for you; if not, please reopen this issue. The JPA support should now be considered deprecated in VoK.

**Comment by kskyle** [comment]
hmm.. I still get the:

`ERROR c.vaadin.server.DefaultErrorHandler - 
java.lang.ClassCastException: com.github.vok.framework.sql2o.vaadin.LikeFilter cannot be cast to java.lang.Void
        at com.vaadin.data.provider.DataProvider$2.combineFilters(DataProvider.java:217)
        at com.vaadin.data.provider.ConfigurableFilterDataProviderWrapper.getFilter(ConfigurableFilterDataProviderWrapper.java:59)
        at com.vaadin.data.provider.DataProviderWrapper.size(DataProviderWrapper.java:86)
        at com.vaadin.data.provider.DataProviderWrapper.size(DataProviderWrapper.java:85)
        at com.vaadin.data.provider.DataCommunicator.getDataProviderSize(DataCommunicator.java:739)
        at com.vaadin.data.provider.DataCommunicator.sendDataToClient(DataCommunicator.java:329)
        at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:313)
        at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:126)
        at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124)
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:381)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:224)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
`


HEre's some example code: 
```


data class Person(var firstName: String, var lastName: String, var sotu: String)


/**
 * This is the root (or main) view. MyUI initially shows view whose name is "" (an empty string).
 * @author mvy
 */

@AutoView("")
class WelcomeView: VerticalLayout(), View {


    private lateinit  var personGrid: Grid<Person>
    private lateinit  var firstNameFilter: TextField
    var persons = listOf<Person>(Person("kari", "skytta", "021278"), Person("matti", "meikalainen", "011178"))

    var personsListProvider = ListDataProvider<Person>(persons).withConfigurableFilter()


    companion object {
        fun navigateTo() = navigateToView<WelcomeView>()
    }

    init {
        isMargin = false
        label("Vaadin On Kotlin") {
            w = fillParent
            addStyleNames(ValoTheme.LABEL_H1, ValoTheme.LABEL_COLORED)
        }


        personGrid = grid(Person::class, "List of Persons", dataProvider = personsListProvider.withConfigurableFilter()) {
            expandRatio = 1f;
            setSizeFull()

            column(Person::firstName) {
                //isEditable = true
                isSortable = true
            }

            addColumn({ "Show" }, ButtonRenderer<Person>({ event -> null }))
            addColumn({ "Edit" }, ButtonRenderer<Person>({ event -> null }))
            addColumn({ "Delete" }, ButtonRenderer<Person>({ event -> null }))



            // automatically create filters, based on the types of values present in particular columns.
            appendHeaderRow().generateFilterComponents(this, Person::class)

        }

        
      }

   override fun enter(event: ViewChangeListener.ViewChangeEvent?) {
    }
}





```

**Comment by mvysny** [comment]
Thanks! Let me look at that.

**Comment by skoude** [comment]
hmm.. I still get the:

`ERROR c.vaadin.server.DefaultErrorHandler - 
java.lang.ClassCastException: com.github.vok.framework.sql2o.vaadin.LikeFilter cannot be cast to java.lang.Void
        at com.vaadin.data.provider.DataProvider$2.combineFilters(DataProvider.java:217)
        at com.vaadin.data.provider.ConfigurableFilterDataProviderWrapper.getFilter(ConfigurableFilterDataProviderWrapper.java:59)
        at com.vaadin.data.provider.DataProviderWrapper.size(DataProviderWrapper.java:86)
        at com.vaadin.data.provider.DataProviderWrapper.size(DataProviderWrapper.java:85)
        at com.vaadin.data.provider.DataCommunicator.getDataProviderSize(DataCommunicator.java:739)
        at com.vaadin.data.provider.DataCommunicator.sendDataToClient(DataCommunicator.java:329)
        at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:313)
        at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:126)
        at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124)
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:381)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:224)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
`


HEre's some example code: 
```


data class Person(var firstName: String, var lastName: String, var sotu: String)


/**
 * This is the root (or main) view. MyUI initially shows view whose name is "" (an empty string).
 * @author mvy
 */

@AutoView("")
class WelcomeView: VerticalLayout(), View {


    private lateinit  var personGrid: Grid<Person>
    private lateinit  var firstNameFilter: TextField
    var persons = listOf<Person>(Person("kari", "skytta", "021278"), Person("matti", "meikalainen", "011178"))

    var personsListProvider = ListDataProvider<Person>(persons).withConfigurableFilter()


    companion object {
        fun navigateTo() = navigateToView<WelcomeView>()
    }

    init {
        isMargin = false
        label("Vaadin On Kotlin") {
            w = fillParent
            addStyleNames(ValoTheme.LABEL_H1, ValoTheme.LABEL_COLORED)
        }


        personGrid = grid(Person::class, "List of Persons", dataProvider = personsListProvider.withConfigurableFilter()) {
            expandRatio = 1f;
            setSizeFull()

            column(Person::firstName) {
                //isEditable = true
                isSortable = true
            }

            addColumn({ "Show" }, ButtonRenderer<Person>({ event -> null }))
            addColumn({ "Edit" }, ButtonRenderer<Person>({ event -> null }))
            addColumn({ "Delete" }, ButtonRenderer<Person>({ event -> null }))



            // automatically create filters, based on the types of values present in particular columns.
            appendHeaderRow().generateFilterComponents(this, Person::class)

        }

        
      }

   override fun enter(event: ViewChangeListener.ViewChangeEvent?) {
    }
}





```

**Comment by mvysny** [comment]
Okay there are two bugs actually - one is that the LikeFilter was not behaving properly with in-memory filtering. That is now fixed.
The other one is apparently in Vaadin: you can set filter to `ListDataProvider<String>(listOf("foo")).withConfigurableFilter()` but you can't set filter to `ListDataProvider<String>(listOf("foo")).withConfigurableFilter().withConfigurableFilter()`. I'll create a bug report at Vaadin; meanwhile as a workaround just drop the second call to `withConfigurableFilter()` in the `grid()` stanza.

**Comment by mvysny** [comment]
Filed in a Vaadin bug: https://github.com/vaadin/framework/issues/9664

**Comment by mvysny** [comment]
Please let me know if the workaround of removing the `withConfigurableFilter()` works for you.

**Comment by skoude** [comment]
Brilliant, now it works perfectly :D  You can close this now.

**Comment by skoude** [comment]
closing myself..
