### ISSUE TITLE
vok-example-flow-sql2o failing with appRun - Could not find ... org.webjars.bower:vaadin-valo-theme:[2.0.0,3)

### ISSUE THREAD

**Issue by WakeRealityDev** [mvysny/vaadin-on-kotlin#8]
Hello. Following the instructions on the README for the project, it's failing on 

    ./gradlew vok-example-flow-sql2o:appRun

Error:

    Execution failed for task ':vok-example-flow-sql2o:appRun'.
    > Could not resolve all dependencies for configuration ':vok-example-flow-sql2o:compile'.
    > Could not find any version that matches org.webjars.bower:vaadin-valo-theme:[2.0.0,3).
     Versions that do not match:
         2.0.0-alpha5
         2.0.0-alpha4
         2.0.0-alpha3
         0.3.2
     Required by:
         project :vok-example-flow-sql2o > project :vok-framework-v10-sql2o > project :vok-util-vaadin10 > com.github.vok.karibudsl:karibu-dsl-v10:0.2.16 > com.vaadin:vaadin:10.0.0.alpha11 > com.vaadin:vaadin-dialog-flow:1.0.0.alpha4 > org.webjars.bower:vaadin-dialog:2.0.0-alpha1
         project :vok-example-flow-sql2o > project :vok-framework-v10-sql2o > project :vok-util-vaadin10 > com.github.vok.karibudsl:karibu-dsl-v10:0.2.16 > com.vaadin:vaadin:10.0.0.alpha11 > com.vaadin:vaadin-combo-box-flow:1.0.0.alpha5 > org.webjars.bower:vaadin-combo-box:3.0.1 > org.webjars.bower:vaadin-overlay:2.0.1

**Comment by mvysny** [comment]
Thanks! Sorry about that. This started to happen when I moved from bower to webjars, and I only found out about this recently. Still trying to find a cure for this.

I suspect that the problem lies in a fact that the `appRun` task somehow does not trigger the `io.spring.dependency-management` plugin and the
```
dependencyManagement {
    imports { mavenBom "com.vaadin:vaadin-bom:$vaadin10_version" }
}
```
stanza. If you comment out these three lines, even `./gradlew build` starts to fail.

We need to find out why the dependency-management-plugin is skipped or ignored when `appRun` task is invoked.

**Comment by WakeRealityDev** [comment]
Thank you. The demo now runs.  However, should "+ New Review" work? It fails with "Internal error
Please notify the administrator."

**Comment by mvysny** [comment]
Yeah it should definitely work. Can you please open a new bug for that?

**Comment by mvysny** [comment]
Fixed creating new Review - there was a NPE: 051dbc194f8dfff39f9bb18379f4344646ef866a

**Comment by WakeRealityDev** [comment]
New review now works, edit is still crashing.  I did a full github checkout and clean build

**Comment by mvysny** [comment]
Yeah, the edit crash is this one: https://github.com/mvysny/karibu-dsl/issues/3 I'll try to implement the workaround.

**Comment by mvysny** [comment]
Ok, workaround worked.

**Comment by WakeRealityDev** [comment]
Edit confirmed to open now. Thank you.
